/**
 * The project data model: `Project → Track[] → Clip`.
 *
 * These are plain, serializable descriptions of the arrangement — they hold no audio
 * nodes and no `AudioContext`. The live audio graph (built in later steps) is derived
 * from this model. Keeping the model pure is what lets us persist it to IndexedDB and
 * unit-test it without a browser.
 *
 * Editing model reminder: clips own their `AudioBuffer` and edits are destructive
 * (a new buffer replaces the old one); the pedalboard FX layer is separate and
 * non-destructive. See the design spec.
 */

import type { EffectState } from '../effects/types.js';

/** Opaque-ish string id. Generated by `createId`. */
export type Id = string;

/** A single audio clip placed on a track. */
export interface Clip {
  readonly id: Id;
  /** Decoded audio for this clip. Replaced wholesale by destructive buffer-ops. */
  buffer: AudioBuffer;
  /** Start position on the timeline, in seconds from the project origin. */
  start: number;
  /** Display name (e.g. the source filename). */
  name: string;
  /** Seconds of the buffer's HEAD to skip (non-destructive left trim). Default 0. */
  trimStart?: number;
  /** Seconds of the buffer's TAIL to skip (non-destructive right trim). Default 0. */
  trimEnd?: number;
}

/** A track: an ordered lane of clips plus its mixer state. */
export interface Track {
  readonly id: Id;
  name: string;
  clips: Clip[];
  /** Linear gain 0..1 (UI shows 0..100). */
  gain: number;
  /** Stereo pan -1 (L) .. 0 (C) .. +1 (R). */
  pan: number;
  muted: boolean;
  soloed: boolean;
  /**
   * The track's non-destructive pedalboard chain, in signal order (index 0 first). Optional so
   * projects/tests predating the effects layer stay valid; treat a missing value as `[]`.
   */
  effects?: EffectState[];
}

/** The whole project: tracks + global tempo metadata. */
export interface Project {
  readonly id: Id;
  name: string;
  tracks: Track[];
  /** Beats per minute — drives the grid/snap UI (not yet wired). */
  bpm: number;
  /** Time-signature numerator/denominator, e.g. [4, 4]. */
  timeSignature: readonly [number, number];
}
